<a href="https://colab.research.google.com/github/jackarl/programacion_analitica/blob/main/REGEX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Expresiones Regularres

In [2]:
texto = 'El 10 de agosto de 2025, María Pérez envió un correo electrónico a la dirección maria.perez@email.com solicitando información sobre el producto X-200. Su número de teléfono es +34 612-345-678. Además, visitó la web https://www.ejemplo.com para consultar precios y disponibilidad. El servidor registró el acceso desde la IP 192.168.1.15 a las 14:23:56, y se detectó un error en el log con código ERR500. En Twitter, el usuario @DataAnalyst comentó: "Los modelos de IA son el futuro #MachineLearning #IA2025". El totaal de la compra fue de $199.99, y el cliente pagó con tarjeta VISA terminada en 1234. Por otro lado, el DNI de Juan García es 12345678Z y su código postal 28080. Para más información, puede llamar al 911 234 567 o visitar www.informacion.es. Recordamos que las feechas límite para inscripción son 2025-09-30 y 2025-10-15.'

El 10 de agosto de 2025, María Pérez envió un correo electrónico a la dirección maria.perez@email.com solicitando información sobre el producto X-200. Su número de teléfono es +34 612-345-678. Además, visitó la web https://www.ejemplo.com para consultar precios y disponibilidad. El servidor registró el acceso desde la IP 192.168.1.15 a las 14:23:56, y se detectó un error en el log con código ERR500. En Twitter, el usuario @DataAnalyst comentó: "Los modelos de IA son el futuro #MachineLearning #IA2025". El totaal de la compra fue de $199.99, y el cliente pagó con tarjeta VISA terminada en 1234. Por otro lado, el DNI de Juan García es 12345678Z y su código postal 28080. Para más información, puede llamar al 911 234 567 o visitar www.informacion.es. Recordamos que las feechas límite para inscripción son 2025-09-30 y 2025-10-15.

In [3]:
import re


1.   Extraer todas las direcciones de correo electrónico.

In [4]:
correo = re.findall(r'\s[A-Za-z0-9._%$*!?+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', texto) # \comienza con un espacio literal seguido del conjunto delimitado por [] donde hay letras May y min de la a a la z numeros del 0 al 9 y acepta todos los caracteres especiales#$%.
print(correo)                                                                          # seguido del @ literal[de la a a z May-min] seguido de . literal [de la a a la z | denota que pueden ser mayusculas o minusculas] \b se determina 'boundary' como fin del texto

#FUENTE DE ESTUDIO UDEMY REGEX https://www.udemy.com/course/the-modern-python3-bootcamp/

[' maria.perez@email.com']


2.   Extraer todas las URLs (con o sin protocolo).

In [5]:
protocol = 'https://'
URL_S = re.findall(r'www\.[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', texto) # .com = \.[A-Z|a-z]{2,}\b
print(URL_S)

['www.ejemplo.com', 'www.informacion.es']


In [6]:
# clean = re.sub(r'https?//\S+|www\.\S+', '', texto)
# print(clean)

3.   Validar y extraer números de teléfono en formato internacional y nacional.

In [7]:
tel = re.search(r'\+\d{2}\s\d{3}-\d{3}-\d{3}', texto)
print(tel)

<re.Match object; span=(176, 191), match='+34 612-345-678'>


In [8]:
telefono = re.findall(r'\d{3} \d{3} \d{3}',texto)
print(telefono)

['911 234 567']


In [9]:
# test = re.findall(r'(\+\d{2}\s|\d{3}) (\s\d{3}|-\d{3}) (\s\d{3}|-\d{3}) (\s\d{3}|-\d{3})', texto) #CODIGO NO ROMPE PERO NO DA OUTPUT, POR
# print(test)

4.   Extraer fechas en formato yyyy-MM-dd.

In [10]:
fechas = re.findall(r'\d{4}-\d{2}-\d{2}', texto)
print(fechas)

['2025-09-30', '2025-10-15']


5.   Extraer códigos postales de 5 dígitos.

In [11]:
postal = re.findall(r'\d{5}\W', texto)
print(f'El codigo postal es: {postal}')

El codigo postal es: ['28080.']


6.   Extraer DNI (8 dígitos seguidos de letra mayúscula).

In [12]:
DNI = re.findall(r'\d+[A-Z]', texto)
DNI

['12345678Z']

7.   Extraer menciones de Twitter.

In [13]:
twetter = re.findall(r' \@\w+', texto)
print(twetter)

[' @DataAnalyst']


8.   Extraer hashtags.

In [14]:
hashtag = re.findall(r'#\w+', texto)
print(hashtag)

['#MachineLearning', '#IA2025']


9.   Extraer direcciones IP.  IP 192.168.1.15

In [15]:
ip = re.findall(r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}', texto)
print(ip)

['192.168.1.15']


10. Extraer importes monetarios (con $ y decimales).

In [16]:
AMOUNT = re.findall(r'\$\d+\.\d{2}', texto)
print(AMOUNT)

['$199.99']


El totaal de la compra fue de $199.99, y el cliente pagó con tarjeta VISA terminada en 1234. Por otro lado, el DNI de Juan García es 12345678Z y su código postal 28080. Para más información, puede llamar al 911 234 567 o visitar www.informacion.es. Recordamos que las feechas límite para inscripción son 2025-09-30 y 2025-10-15.